name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Setup Rust 
        uses: actions-rs/toolchain@v1.0.6
        with:
          override: true
          profile: minimal
          toolchain: nightly
          components: rust-src

      - name: Setup extra tools
        run: |
          sudo apt update && sudo apt install -y \
            gcc-i686-linux-gnu \
            build-essential \
            xorriso \
            grub-pc \
            nasm

      - name: build / run
        run: cargo run