name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello world
        uses: ./
        id: hello
        with:
          who-to-greet: 'abc'
      - name: show result
        run: echo "The time was ${{ steps.hello.outputs.time }}."