name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          sudo apt update && sudo apt install -y \
            gcc-i686-linux-gnu \
            build-essential \
            qemu-system \
            xorriso \
            grub-pc \
            nasm \
            curl
      - name: done
        run: |
          nasm --version