name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt update && sudo apt install -y \
            gcc-i686-linux-gnu \
            build-essential \
            qemu-system \
            xorriso \
            grub-pc \
            nasm \
            curl
      - name: Install rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - \
            -y \
            --default-toolchain nightly \
            --component rust-src
      - name: build / run
        run: |
          source "$HOME/.cargo/env"
          cargo run